Replace Travis with GitHub Actions
lmc-eu/php-coding-standard pull request #43
Opened 2020-10-30 20:42 UTC by OndraM

Move builds to GitHub actions, but it should still do the same as on Travis.

(Next step in separate PRs will be Composer 2, then PHP 8).

2020-10-30 20:43 UTC, OndraM commented on .travis.yml
> -language: php
F

2020-10-31 16:08 UTC, jirinovak approved these changes

2020-11-02 08:48 UTC, MortalFlesh requested changes

2020-11-02 08:48 UTC, MortalFlesh commented on .github/workflows/tests.yaml
> +            tools: composer:v2 # TODO update to v2
I dont think, this is correct - it should either be `:v1` or without a todo comment

2020-11-02 08:50 UTC, OndraM commented on .github/workflows/tests.yaml
> +            tools: composer:v2 # TODO update to v2
```suggestion
            tools: composer:v1 # TODO update to v2
```

2020-11-02 08:51 UTC, MortalFlesh approved these changes

2020-11-02 09:22 UTC, merged