Update dependencies
lmc-eu/php-coding-standard pull request #75
Opened 2022-04-05 08:30 UTC by MortalFlesh

2022-04-11 09:20 UTC, jirinovak approved these changes

2022-04-11 12:36 UTC, OndraM requested changes

2022-04-11 12:36 UTC, OndraM commented on composer.json
> +        "friendsofphp/php-cs-fixer": "dev-feature/fix-union-types-in-phpdocs as 3.8.0",
As we discussed, this will make it not installable without copying `repositories` block to every composer.json using `lmc/coding-standard`  😬

2022-04-20 06:45 UTC, MortalFlesh commented on ecs-8.0.php
> +        $services->set(PropertyTypeHintSniff::class);
Slevomat type hint sniffs handles superfluous annotations - I could not figure out how to remove them otherwise.

2022-04-20 13:32 UTC, freiondrej-lmc commented on ecs.php
> +        $parameters->set(Option::PARALLEL, true);
@MortalFlesh is this necessary? symplify/easy-coding-standard:^10 seems to enable this by default as well :)

2022-04-21 13:04 UTC, freiondrej-lmc requested changes
parameters->set(Option::PARALLEL, true); is not necessary IMO as it is on by default in ^10.0 :)

2024-04-16 08:04 UTC, closed without merging